### ISSUE TITLE
[BUG] Removed [SYS][doNotCheckReferer] configuration from core throws exception error

### ISSUE THREAD

**Issue by Patta** [FriendsOfTYPO3/jumpurl#11]
Since TYPO3 7.6.25 and 8.7.11 the `[SYS][doNotCheckReferer]` configuration is removed.
See: https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/8.7.x/Important-83768-RemoveReferrerCheck.html

In current jumpurl version 7.1.1 the configuration is used for referrer check.
See: https://docs.typo3.org/typo3cms/extensions/jumpurl/Configuration/Index.html#typo3-conf-vars

Now the be log throws exception errors:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: The jumpUrl request was triggered by an illegal referrer. | RuntimeException thrown in file /.../typo3conf/ext/jumpurl/Classes/JumpUrlHandler.php in line 66. Requested URL: ...

**Comment by SventB** [comment]
I also had this error and it's strange: In every browser, the jumpurl link worked, but not on my Android smartphone in the Google Mail app. Here, the link is opened in the Google Mail browser (which is based on Chrome) and the "illegal referrer" occured. But not when opening the same link in the Chrome browser on my smartphone.

**Comment by bmack** [comment]
Hey, can one of you create a PR for that?

**Comment by Patta** [comment]
@bmack should be fixed in PR #13
