### ISSUE TITLE
Not compatiblewith TYPO3 v9 LTS

### ISSUE THREAD

**Issue by luberti** [FriendsOfTYPO3/jumpurl#16]
Hello,we have found that jumpurl is notcompatible with TYPO3 9 : there are three calls to removed methods.
I would like to knowif there is any plan to fix this and if there is a timing.
In any case I and my colleagues could be in a position to contribute to this and I wonder if could be sensible to open a new branch for this.
Best regards

**Comment by masi** [comment]
> 
> there are three calls to removed methods.

Which ones? Looking at the code I find none. Only GeneralUtility::getFileAbsFileName() makes trouble as it takes now only 1 parameter.

**Comment by luberti** [comment]
sorry masi, I have double cheked using the scan extension files and as you pint out there only  GeneralUtility::getFileAbsFileName() marked as 

Breaking: #80700 - Deprecated functionality removed

the other two strong alert are only deprecations

**Comment by bmack** [comment]
Done. Sorry for the delay!

Check out Release 7.8.0, also on TER and packagist.
