### ISSUE TITLE
TYPO3 10 compatibiliy

### ISSUE THREAD

**Issue by AnatoliZich** [FriendsOfTYPO3/jumpurl#21]
Hey,

im currently working on getting `direct_mail` compatible with TYPO3 10 which depends on this package. Would love to see this getting ready for the upcoming 10 LTS version :slightly_smiling_face:

**Comment by bmack** [comment]
Could you check out https://github.com/FriendsOfTYPO3/jumpurl/pull/22 and see if it is working for you on TYPO3 v10?

**Comment by AnatoliZich** [comment]
Thanks for the quick response! I actually didn't expect to see it that soon :slightly_smiling_face:
I'll test it today or early next week.

**Comment by AnatoliZich** [comment]
Sorry for the late answer. I got some more pressing matters to attend to but i'll continue to test next week

**Comment by AnatoliZich** [comment]
Works just fine for me. This is what i tested:
* enabling jumpurl for a regular typolink. It shows the juHash and jumpurl parameters and redirects without any problems
* Writing a middleware that executes just before the new JumpurlHandler middleware. This is what i needed for direct mail
* setting the secure flag for a typolink and point it to a .htaccess protected file. juHash, jumpurl, locationData Parameters are all shown correctly

No issues whatsoever. Green light for that PR from me :+1: 

Thank you very much, Benny!
