### ISSUE TITLE
TypeError in backend module "redirects" with "jumpurl" installed

### ISSUE THREAD

**Issue by tobenschmidt** [FriendsOfTYPO3/jumpurl#23]
TYPO3 10.4.1
redirects 10.4.1
jumpurl 8.0.0
PHP 7.4

Redirects with an external URL in field _target_ throw the following error in backend module _redirects_:

```
(1/1) TypeError

Return value of FoT3\Jumpurl\JumpUrlProcessor::getTypoScriptFrontendController() must be an instance of TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController, null returned

in [...]/public/typo3conf/ext/jumpurl/Classes/JumpUrlProcessor.php line 208

protected function getTypoScriptFrontendController(): TypoScriptFrontendController
{
    return $this->frontendController ?? $GLOBALS['TSFE'];
}
```

**Comment by M-a-r-n-o** [comment]
I´ve got the same problem. As a workaround i replaced the function in "Classes/JumpUrlProcessor.php" with this one:
`    
protected function getTypoScriptFrontendController(): TypoScriptFrontendController
    {

        if ($this->frontendController instanceof TypoScriptFrontendController) {
            return $this->frontendController;
        }

        if(
            isset($GLOBALS['TSFE']) &&
            !empty($GLOBALS['TSFE'])
        ){
            return $GLOBALS['TSFE'];
        }

        $this->frontendController = GeneralUtility::makeInstance(
            TypoScriptFrontendController::class,
            null,
            GeneralUtility::_GP('id'),
            (int)GeneralUtility::_GP('type')
        );
        $this->frontendController->sys_page = GeneralUtility::makeInstance(\TYPO3\CMS\Frontend\Page\PageRepository::class);
        $this->frontendController->tmpl = GeneralUtility::makeInstance(\TYPO3\CMS\Core\TypoScript\TemplateService::class);

        return $this->frontendController;
    }
`
But it´s totally not tested.

**Comment by utrotzek** [comment]
I have the same problem when jumpurl and redirects are both installed. Because solution above did not work for me I'm using this one:

file: Classes/JumpUrlProcessor.php

```
    protected function getTypoScriptFrontendController(): ?TypoScriptFrontendController
    {
        return $this->frontendController ?? TypoScriptFrontendController::getGlobalInstance();
    }
```

Which makes sure  the redirects module is accessible again. But I have to figure out if jumpurl is still working properly.

**Comment by tobenschmidt** [comment]
The origin of this error is the creation of frontend links in backend context in the redirects module. In class _TYPO3\CMS\Frontend\Typolink\AbstractTypolinkBuilder_ there is a kind of workaround in method `getTypoScriptFrontendController` to avoid errors like this:

```PHP
/**
 * @return TypoScriptFrontendController
 */
public function getTypoScriptFrontendController(): TypoScriptFrontendController
{
    if ($this->typoScriptFrontendController instanceof TypoScriptFrontendController) {
        return $this->typoScriptFrontendController;
    }

    // This usually happens when typolink is created by the TYPO3 Backend, where no TSFE object
    // is there. This functionality is currently completely internal, as these links cannot be
    // created properly from the Backend.
    // However, this is added to avoid any exceptions when trying to create a link.
    // Detecting the "first" site usually comes from the fact that TSFE needs to be instantiated
    // during tests
    $request = $GLOBALS['TYPO3_REQUEST'] ?? ServerRequestFactory::fromGlobals();
    $site = $request->getAttribute('site');
    if (!$site instanceof Site) {
        $sites = GeneralUtility::makeInstance(SiteFinder::class)->getAllSites();
        $site = reset($sites);
        if (!$site instanceof Site) {
            $site = new NullSite();
        }
    }
    $language = $request->getAttribute('language');
    if (!$language instanceof SiteLanguage) {
        $language = $site->getDefaultLanguage();
    }

    $id = $request->getQueryParams()['id'] ?? $request->getParsedBody()['id'] ?? $site->getRootPageId();
    $type = $request->getQueryParams()['type'] ?? $request->getParsedBody()['type'] ?? '0';

    $this->typoScriptFrontendController = GeneralUtility::makeInstance(
        TypoScriptFrontendController::class,
        GeneralUtility::makeInstance(Context::class),
        $site,
        $language,
        $request->getAttribute('routing', new PageArguments((int)$id, (string)$type, []))
    );
    $this->typoScriptFrontendController->sys_page = GeneralUtility::makeInstance(PageRepository::class);
    $this->typoScriptFrontendController->tmpl = GeneralUtility::makeInstance(TemplateService::class);

    return $this->typoScriptFrontendController;
}
```

Unfortunately the method `getTypoScriptFrontendController` in class _FoT3\Jumpurl\JumpUrlProcessor_ is missing the workaround:

```PHP
protected function getTypoScriptFrontendController(): TypoScriptFrontendController
{
    return $this->frontendController ?? $GLOBALS['TSFE'];
}
```

The easy solution to this problem would be a little copy and paste from `AbstractTypoLinkBuilder` to `JumpUrlProcessor`. The more elegant solution would be to use the TypoScript Frontend Controller from `AbstractTypoLinkBuilder` in `JumpUrlProcessor` by passing it in the constructor in method `processUrl`. But this would require a change in system extension _frontend_:

```PHP
$urlProcessor = GeneralUtility::makeInstance($configuration['processor'], $this->getTypoScriptFrontendController());
```
