### ISSUE TITLE
Error with latest version in 9.5

### ISSUE THREAD

**Issue by matin73** [FriendsOfTYPO3/jumpurl#24]
After updating to version 8.0 I get error on root page in page view backend:

Return value of FoT3\Jumpurl\JumpUrlProcessor::getTypoScriptFrontendController() must be an instance of TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController, null returned

downgrading to 7.8 solves this problem.

**Comment by bernd-reindl** [comment]
Same here in TYPO3 10.4.6.

I have solved it by modifying the function getTypoScriptFrontendController() in class \FoT3\Jumpurl\JumpUrlProcessor like the function getTypoScriptFrontendController() in \TYPO3\CMS\Frontend\Typolink\AbstractTypolinkBuilder.

Best regards
Bernd Reindl

See changes:
- use directives
- __construct()
- getTypoScriptFrontendController()

[JumpUrlProcessor.zip](https://github.com/FriendsOfTYPO3/jumpurl/files/5027533/JumpUrlProcessor.zip)

**Comment by jokumer** [comment]
Same here:
Version 8.0.0
TYPO3 10.4.9 (Mac+DDEV, Linux+Docker)

Named error occurse when open backend module "Redirect".

**Comment by Patta** [comment]
Same here on redirect backend module.

TYPO3 10.4.12
PHP 7.4.14
jumpurl 8.0.0
composer mode

`[CRITICAL] request="e35d843716a95" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of FoT3\Jumpurl\JumpUrlProcessor::getTypoScriptFrontendController() must be an instance of TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController, null returned | TypeError thrown in file REMOVED\private\typo3conf\ext\jumpurl\Classes\JumpUrlProcessor.php in line 208. Requested URL: REMOVED.localhost/typo3/index.php?route=%2Fmodule%2Fsite%2Fredirects&token=--AnonymizedToken-- - {"TYPO3_MODE":"BE","exception":{}}`

**Comment by Patta** [comment]
#23 #26
