### ISSUE TITLE
Error in Typo3 v. 10.4.xx after click on module redirects

### ISSUE THREAD

**Issue by fennecgit** [FriendsOfTYPO3/jumpurl#28]
Following error occures:

Return value of FoT3\Jumpurl\JumpUrlProcessor::getTypoScriptFrontendController() must be an instance of TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController, null returned

Solution:

After changing lines in file jumpurl\Classes\JumpUrlProcessor.php after line 208:

     protected function getTypoScriptFrontendController(): TypoScriptFrontendController
    {
        return $this->frontendController ?? $GLOBALS['TSFE'];
    } 

in 

   protected function getTypoScriptFrontendController()
    {
        return $this->frontendController ?? $GLOBALS['TSFE'];
    }
everything works fine again.

**Comment by chris246** [comment]
Same in TYPO3 v9
