### ISSUE TITLE
Redirects tool in Typo3 11 with PHP 8 generates Undefined array key "TSFE"

### ISSUE THREAD

**Issue by tomashavner** [FriendsOfTYPO3/jumpurl#36]
Hi,

In Typo3 11.5.16 and PHP8, if you first select a page in the pagetree and then click "Redirects" in the tool menu you get:
PHP Warning: Undefined array key "TSFE" in /var/www/typo3.sol.lu.se/typo3conf/ext/jumpurl/Classes/JumpUrlProcessor.php line 41
Not a huge problem but annoying. Changing line 41 to:
$this->frontendController = $typoScriptFrontendController ?? ($GLOBALS['TSFE'] ?? null);
solves the problem.

Kind regards

Tomas

**Comment by bmack** [comment]
see #35 which fixes the problem, but the PR needs work

**Comment by imminger** [comment]
Redirect module is still broken. [tomashavner](https://github.com/tomashavner)s suggested fix works for me, but it's not part of #39
