### ISSUE TITLE
Jumpurl causes PHP warnings about undefined array key while null coalescing

### ISSUE THREAD

**Issue by pwilladt** [FriendsOfTYPO3/jumpurl#37]
Hello,

using jumpurl in a freshly updated typo3 installation throws warnings.

System configuration: jumpurl 8.0.3, typo3 11.5.17 and PHP 8.0.

Warning message: Core: Error handler (FE): PHP Warning: Undefined array key "jumpurl" in /www/htdocs/w0063ec2/cm3/typo3conf/ext/jumpurl/Classes/Middleware/JumpUrlHandler.php line 60

To me, the typecast in line 60 appears to be guilty.
Putting braces around the expression with the null coalescing operator removes the warnings.

$jumpUrl = (string) ( $request->getQueryParams()['jumpurl'] ?? '');

Kind regards
peter

**Comment by webian** [comment]
Same, adding brackets as suggested removed the warning in PHP 8.1

**Comment by bmack** [comment]
see #35 which fixes the problem, but the PR needs work

**Comment by mediaessenz** [comment]
Since this issues was solved with the merge of https://github.com/FriendsOfTYPO3/jumpurl/pull/39 , it can be closed.
