### ISSUE TITLE
Not compatible with TYPO3 v8 LTS (8.7) 

### ISSUE THREAD

**Issue by fischhase** [FriendsOfTYPO3/jumpurl#4]
Hallo dear friends of TYPO3,

I am updating a TYPO3 installation with direct mail. Direct mail depense on jump url, so I would like to ask, if you will provide a version für version 8.7 LTS. People longing for it:
[e.g. Direct Mail Developers Comment](https://github.com/kartolo/direct_mail/issues/53)

Thanks and regards :-)
Martin

**Comment by bmack** [comment]
Hey,

it looks to me that the only concern is the version constraint, the rest should be compatible? Can you confirm this or help me with testing? Releasing a v8-core-compatible version is not the problem but it should still work for Direct Mail as well....

I could send you a prepared version of the extension as zip etc, if you'd like?

**Comment by fischhase** [comment]
Hi Benni,

I could activate the extension by ignoring the version constraint 
without error messages, so maybe its just the version constraint. I 
could not really test the functionality, because I have no direct 
implementation. I only need it for direct mail. If you have a short 
expamle, I can test the functionality of cause.

bye
Martin


Am 21.04.2017 um 17:10 schrieb Benni:

**Comment by bmack** [comment]
Hey @fischhase - just published version 7.7.0 to TER and packagist, adding support for TYPO3 v8 LTS.

**Comment by fischhase** [comment]
great. Thankyou Benni :-)
